[package]
name = "tests"
description = "Tests for the Lumine HTTP web server."
repository = "https://github.com/Ellen-desu/lumine"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT"

[dependencies]
http = "1.4"
lumine = { version = "0", path = "../lumine"}
tokio = { version = "1.52", features = ["macros", "rt"] }
async-trait = "0.1"
bytes = "1.12"

[[test]]
name = "routing"
path = "routing.rs"

[[test]]
name = "middleware"
path = "middleware.rs"

[[test]]
name = "dispatch"
path = "dispatch.rs"

[[test]]
name = "reader"
path = "reader.rs"

[[test]]
name = "writer"
path = "writer.rs"
