[package]
name = "lumine"
description = "A lightweight async HTTP web framework for Rust."
version = "0.6.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ellen-desu/lumine"
categories = ["web-programming::http-server", "web-programming", "network-programming"]
keywords = ["http", "web-server", "network", "lightweight", "async"]

[dependencies]
http = "1.4"
form_urlencoded = "1.2"
tokio = { version =  "1.52", features = ["net", "rt","io-util", "fs", "time"] }
async-trait = "0.1"

infer = { version = "0.19", optional = true }
time = { version = "0.3", features = ["formatting", "macros"], optional = true }
tokio-rustls = { version = "0.26", optional = true }

[features]
filestream = ["dep:infer"]
date = ["dep:time"]
tls = ["dep:tokio-rustls"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
