[package]
name = "examples"
description = "Example of using the Lumine HTTP web server."
repository = "https://github.com/ouzuka-m/lumine"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT"

[dependencies]
lumine = { version = "0", path = "../lumine", features = ["filestream", "tls"] }
tokio = { version = "1.53", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Middleware
async-trait = "0.1"

# TLS
tokio-rustls = { version = "0.26" }
rustls-pki-types = { version = "1.15" }

[[example]]
name = "hello_world"
path = "1_hello_world.rs"

[[example]]
name = "routing"
path = "2_routing.rs"

[[example]]
name = "response"
path = "3_response.rs"

[[example]]
name = "request"
path = "4_request.rs"

[[example]]
name = "parameters"
path = "5_parameters.rs"

[[example]]
name = "middleware"
path = "6_middleware.rs"

[[example]]
name = "tls"
path = "7_tls.rs"

[[example]]
name = "static_files"
path = "8_static_files.rs"
