[package]
name = "examples"
description = "Example of using the Lumine HTTP web server."
repository = "https://github.com/Ellen-desu/lumine"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT"

[dependencies]
lumine = { version = "0", path = "../lumine" }
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[example]]
name = "routing"
path = "routing.rs"

[[example]]
name = "request"
path = "request.rs"

[[example]]
name = "response"
path = "response.rs"

[[example]]
name = "parameters"
path = "parameters.rs"
