[package]
name = "benches"
description = "Performance testing for Lumine HTTP web server."
repository = "https://github.com/ouzuka-m/lumine"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT"

[dependencies]
lumine = { version = "0", path = "../lumine"}
criterion = { version = "0.8", features = ["async_tokio"] }
rand = "0.10"
tokio = { version = "1.53", features = ["rt-multi-thread"] }

[[bench]]
name = "routing"
path = "routing.rs"
harness = false

[[bench]]
name = "reader"
path = "reader.rs"
harness = false
